name: Upload Python Packages to S3

on: [push]

jobs:
  upload-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Ensure S3 Bucket Exists
      run: |
        if ! aws s3 ls "s3://blanco-python-lambda-layers" > /dev/null 2>&1; then
          aws s3 mb "s3://blanco-python-lambda-layers" --region us-east-1
        fi

    - name: Empty S3 Bucket
      run: |
        aws s3 rm s3://blanco-python-lambda-layers --recursive

    - name: Install and Package Requirements
      run: |
        while read requirement; do
          mkdir -p packages/$requirement/python
          python -m pip install $requirement -t packages/$requirement/python
          pushd packages/$requirement
          zip -r ../$requirement.zip .
          popd
        done < requirements.txt


    - name: Upload to S3
      run: |
        for zip_file in packages/*.zip; do
          if [ -f "$zip_file" ]; then
            aws s3 cp "$zip_file" s3://blanco-python-lambda-layers/$(basename "$zip_file")
          fi
        done





